project:
  type: website
  output-dir: _site

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "K-pico"
  navbar:
    right:
      - blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: theme.scss
    css: styles.css



