project:
  type: website
  output-dir: _site

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "kikkupico"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kikkupico
      - icon: linkedin
        href: https://www.linkedin.com/in/ramakrishnan-veeraragavan-725797205/
format:
  html:
    theme: theme.scss
    css: styles.css



